# Generated by Django 4.2.6 on 2023-10-18 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_profile_disliked_profile_liked'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
