# Generated by Django 4.2.6 on 2023-10-17 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_rename_pub_date_course_date_course_introduction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='enrolled',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enrolls', to='courses.course'),
        ),
    ]
