# Generated by Django 4.2.6 on 2023-10-17 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_profile_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='disliked',
            field=models.ManyToManyField(blank=True, null=True, related_name='disliked', to='courses.course'),
        ),
        migrations.AddField(
            model_name='profile',
            name='liked',
            field=models.ManyToManyField(blank=True, null=True, related_name='liked', to='courses.course'),
        ),
    ]
